---
apiVersion: v1
kind: Service
metadata:
  name: imaginary-service
spec:
  selector:
    app: imaginary
  ports:
    - port: 9000
      targetPort: 9000
  type: LoadBalancer
  selector:
    app: imaginary

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: imaginary
spec:
  selector:
    matchLabels:
      app: imaginary
  replicas: 1
  template:
    metadata:
      labels:
        app: imaginary
    spec:
      containers:
      - name: imaginary
        image: h2non/imaginary:latest
        resources:
          requests:
              cpu: "2100m"
        args:
        - -enable-url-source
        - -allowed-origins
        - "http://*.cyverse.org"
        - -disable-endpoints 
        - "form"
        - -concurrency=20
        - -cpus
        - "16"
        ports:
        - containerPort: 9000
        # resources:
          # limits:
          #   cpu: "16"
          # requests:
          #   cpu: "16"

---
 apiVersion: autoscaling/v1
 kind: HorizontalPodAutoscaler
 metadata:
   name: imaginary
 spec:
   scaleTargetRef:
     apiVersion: apps/v1
     kind: Deployment
     name: imaginary
   minReplicas: 2
   maxReplicas: 6
   targetCPUUtilizationPercentage: 95

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: imaginary-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/issuer: "letsencrypt-prod"

spec:
  tls:
  - hosts:
    - img.cyverse.org
    secretName: imaginary-tls
  rules:
  - host: img.cyverse.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: varnish-svc
            port:
              number: 80     
